version: "3"

tasks:
  test:
    cmds:
      - go test ./... -v -cover
    desc: Run Go tests with verbose output
    silent: false

  golangci-lint:
    cmds:
      - |
        docker run --rm -t -v $(pwd):/app -w /app \
          golangci/golangci-lint:v2.6.2 golangci-lint {{default "help" .CLI_ARGS }}
    desc: Run golangci-lint
    silent: true

  lint:
    cmds:
      - task: golangci-lint
        vars:
          CLI_ARGS: "run"
    desc: Run golangci-lint lint
    silent: true
